In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [49]:
p = math.ceil(-0.5)
print (p)

0


In [50]:
X = pd.read_csv('/home/nikhila/Quantiphi/assignment2/mnist_train.csv')

In [29]:
X.head()

5  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.608  0.609  0.610  \
0  0  0    0    0    0    0    0    0    0    0  ...        0      0      0   
1  4  0    0    0    0    0    0    0    0    0  ...        0      0      0   
2  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   
3  9  0    0    0    0    0    0    0    0    0  ...        0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...        0      0      0   

   0.611  0.612  0.613  0.614  0.615  0.616  0.617  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

X.info()

In [51]:
train_data = X.drop(['5'],axis =1)
train_data.shape

(59999, 784)

In [52]:
train_labels = X['5']
train_labels

0        0
1        4
2        1
3        9
4        2
5        1
6        3
7        1
8        4
9        3
10       5
11       3
12       6
13       1
14       7
15       2
16       8
17       6
18       9
19       4
20       0
21       9
22       1
23       1
24       2
25       4
26       3
27       2
28       7
29       3
        ..
59969    2
59970    2
59971    0
59972    9
59973    2
59974    4
59975    6
59976    7
59977    3
59978    1
59979    3
59980    6
59981    6
59982    2
59983    1
59984    2
59985    6
59986    0
59987    7
59988    8
59989    9
59990    2
59991    9
59992    5
59993    1
59994    8
59995    3
59996    5
59997    6
59998    8
Name: 5, Length: 59999, dtype: int64

conv; reLU; pool; FC; Softmax

In [53]:
train_data2 = train_data.values.reshape((train_data.shape[0],28,28), order = 'C')
train_data2.shape

(59999, 28, 28)

In [24]:
#padding
a = np.arange(4).reshape(2,2)
a
b = np.pad(a,1,'constant')
b

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 3, 0],
       [0, 0, 0, 0]])

#filters = shape(3,3), s = 1, p = 1, k = 1 => 1 filter = (3,3,1)

Function conv returns - convmatrix-shape-(59999,28,28)

### Filter

In [60]:
def FIL(fw,fh):
    fil = np.random.randint(5,size = (fw,fh))
    return fil
fil = FIL(3,3)
print (fil)

[[0 3 2]
 [4 2 2]
 [4 0 4]]


### Bias

In [61]:
Wout = train_data2.shape[1]
Hout = train_data2.shape[2]
m = train_data2.shape[0]

def BIAS(m,Wout,Hout):
    bias = np.random.randint(5, size = (m,Wout,Hout))
    return bias

bias = BIAS(m,Wout,Hout)

### Conv

In [62]:
def CONV(train_data2, stride, fw, fh, padding,bias,fil):
    #padding increases input dim by (2,2)
    train_data3 = np.pad(train_data2,padding,'constant')
    #convolving with given stride and given filters
    s = stride
    conv_out = np.zeros((m,Wout,Hout))
    
    for i in range(m):
        for j in range(Wout):
            for k in range(Hout):
                    conv_out[i,j,k] = np.sum(np.multiply(train_data2[i,j:j+fw, k:k+fh],fil)) + bias
                    return conv_out
    

In [94]:
conv_out = CONV(train_data2,1,3,3,1,1,fil)

In [76]:
print (conv_out.shape)
print(m)
print(Wout)

(59999, 28, 28)
59999
28


### Relu

In [95]:
def RELU(conv):
    relu_out = conv>0
   # print(relu_out)
    return relu_out*conv


#fn reLU - returns- (59999,28,28)

In [99]:
relu = RELU(conv_out)
print(relu[1,:,:])
print (relu.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0

### Pool

#fn pool returns - (59999,14,14)

In [98]:
def POOL(reLU, s, pw, ph):
    Wout = train_data2.shape[1]
    Hout = train_data2.shape[2]
    m = train_data2.shape[0]
    for i in range(m):
        for j in range(Wout):
            for k in range(Hout):
                    pool_out[i,math.ceil((j-pw)/s)+1,math.ceil((k-ph)/s)+1] = np.max(reLU[i,j:j+pw, k:k+ph])
                    return pool_out

In [102]:
n = relu.shape[1]*relu.shape[2]
fc_fil = np.random.randint(5,size = (n,10))     #fc filter shape - (784,10) and bias
b = np.zeros((m,10))

### Fully Connected

In [103]:

""""def FC(pool,fc_filter,b):
    m = pool.shape[0]
    n = pool.shape[1]*pool.shape[2]
    fc = pool.reshape(m,n)
    fc = np.dot(fc,fc_filter) + b
    return fc"""
def FC(rel,fc_filter,b):
    m = rel.shape[0]
    n = rel.shape[1]*rel.shape[2]
    fc = rel.reshape(m,n)
    fc = np.dot(fc,fc_filter) + b
    return fc

In [105]:
fc = FC(relu,fc_fil,b)

fc.shape

(59999, 10)

In [109]:
#softmax - output - (n,10)
sfmx = np.zeros((m,10))

### Softmax

In [107]:
def SOFTMAX(fc):
    m = fc.shape[0]
    n = fc.shape[1]
    for i in range(m):
       sfmx[i,:] = (np.exp((fc[i,:]-np.max(fc[i,:])))/(np.sum(np.exp(fc[i,:]-np.max(fc[i,:])))))
    return sfmx
                    
                  

In [112]:
sfmx = SOFTMAX(fc)

sfmx.shape

sfmx[1,:]

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

  """def stable_softmax(X):
    exps = np.exp(X - np.max(X))
    return exps / np.sum(exps)"""

In [ ]:
def pred(sfmx):
    y_hat = 

In [ ]:
def forwardprop():

# BACKPROP

conv_out = conv(train_data2,1,3,3,1,1)
print (conv_out.shape)

reLU = reLU(conv_out)
print (reLU.shape)      #relu - (59999,28,28)

sfmx = softmax(fc)
print (sfmx.shape)      #sfmx - (59999,10)

### Backprop FC

In [ ]:
#dw_fc = np.random.randn(784,10)

def DW_FC(train_labels,sfmx,reLU):
    reLU = reLU.reshape(59999,784)
    dw_fc[]= np.dot(reLU.T,(sfmx - np.ones((m,10)) ))
    return dw_fc

#dw_fc - shape - (784,10)



In [ ]:
#dw_fc = DW_FC(train_labels, sfmx,relu)

In [ ]:
w_fc = np.random.randn(784,10)

def W_FC(w_fc,dw_fc):
    alpha = 0.001
    w_fc = W_fc - alpha*(dw_fc)
    return w_fc

In [ ]:
##### w_fc has to be updated later

In [ ]:
#db_fc = np.random.randn(59999,784,10)

def DB_FC(softmax):
    db_fc = (softmax - np.zeros((59999,10)))
    return db_fc

In [ ]:
db_fc = DB_FC(sfmx)

In [ ]:
def B_FC(dbfc):
    beta = 0.001
    b_fc - = beta*dbfc
    return b_fc

In [ ]:
b_fc = B_FC(db_fc)

### Backprop Conv

In [ ]:
def DW_CONV(softmax,fc_filter,reLU_out,conv_fil):
    drelu_conv = reLU_out > 0
    dw_conv = (softmax - np.zeros((59999,10)))*fc_filter*(reLU_out > 0)*conv_fil
    return dw_conv

In [ ]:
dw_conv = DW_CONV(sfmx, fc_fil, relu, fil)

In [ ]:
fc_fil = W_FC(fc_fil,dw_fc)  

In [ ]:
def FIL_CONV(dws_conv,fil_conv):
    gama = 0.001
    fil_conv += gama*dws_conv
    return fil

In [ ]:
fil = FIL_CONV(dw_conv,fil)

In [ ]:
def DB_CONV(softmax,fc_filter,reLU_out,):
    db_conv = ((softmax - np.zeros((59999,10)))*fc_filter*(reLU_out > 0))/(softmax)
    return db_conv

In [ ]:
def b_conv(db_conv,b_conv):
    lbd = 0.001
    b_conv = b_conv + lbd*db_conv
    return b_conv